version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - VIDEO_SCRAPING_ENDPOINT=${VIDEO_SCRAPING_ENDPOINT}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - frontend
      - elasticsearch
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0 # Use the official Elasticsearch Docker image
    environment:
      - discovery.type=single-node # Set the discovery type to single-node for local use
    ports:
      - "9200:9200" # Expose Elasticsearch on port 9200
    networks:
      - app-network

  redis:
    image: redis:latest # Use official Redis Docker image
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
